plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true
    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    flatDir {
        dir 'libs'
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.4"))
    jarJar(implementation("io.github.llamalad7:mixinextras-forge:0.5.4"))

    // 前置
    implementation fg.deobf("curse.maven:timeless-and-classics-zero-1028108:8141310")
    implementation fg.deobf('libs:funky_effect_lib:1.2.0-mc1.20.1-forge')
    //implementation fg.deobf(files("libs/funky_effect_lib-1.1.1-mc1.20.1-forge.jar"))

    // 联动
    implementation fg.deobf("curse.maven:mekanism-268560:6552911")
    implementation fg.deobf("curse.maven:mekanism-generators-268566:6552914")
    implementation fg.deobf("curse.maven:easy-villagers-400514:7202309")
    // 辅助
    runtimeOnly fg.deobf("curse.maven:advanced-loot-info-1205426:8168726")
    runtimeOnly fg.deobf("curse.maven:jei-238222:7391695")
    runtimeOnly fg.deobf("curse.maven:architectury-api-419699:5137938")
    runtimeOnly fg.deobf("curse.maven:kubejs-238086:5853326")
    runtimeOnly fg.deobf("curse.maven:rhino-416294:6186971")
    runtimeOnly fg.deobf("curse.maven:jade-324717:6855440")
    runtimeOnly fg.deobf("curse.maven:placebo-283644:6274231")
    runtimeOnly fg.deobf("curse.maven:apothic-attributes-898963:5634071")
    runtimeOnly fg.deobf("curse.maven:mmmmmmmmmmmm-225738:6860192")
    runtimeOnly fg.deobf("curse.maven:selene-499980:8076692")
    runtimeOnly fg.deobf("curse.maven:trade-cycling-570431:6497870")
}

mixin {
    add sourceSets.main, 'tbz.mixin.refmap.json'
    config 'tbz.mixins.json'
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version: forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors: mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

    finalizedBy 'reobfJar'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
